### ISSUE TITLE
TypeError: Failed to convert object of type <class 'theano.tensor.var.TensorVariable'> to Tensor

### ISSUE THREAD

**Issue by Rotaka92** [weecology/DeepLidar#12]
Hello,
even if I change os.environ['KERAS_BACKEND']='tensorflow', each time the same error.
Further: Contents: Elemwise{add,no_inplace}.0. Consider casting elements to a supported type.

Thanks

**Comment by bw4sz** [comment]
Without more detail I can't really help, but I my gut here is that your installation of keras has issues. Certainly DeepLidar won't work on a theano backend.

On the good news front, a python package for this work is in development here and has a much friendlier install process to avoid these kind of challenges. 

https://github.com/weecology/DeepForest

```
pip install DeepForest
```

Closing here, welcome to open issue in DeepForest.
